### ISSUE TITLE
Publish with optimistic locking

### ISSUE THREAD

**Issue by ausov** [nouney/helm-gcs#1]
As user,
I want to see optimistic locking error when I try to push when my repository index is not up-to-date
So that I do not overwrite changes in repo index made by someone else at the same time.

As user,
I want to optionally to reload index and retry push when optimistic locking error occurs
So that I can push in simultaneously run automated builds.

---

Design concept proposal:

* when loading index from repo, get GCS $revision on index.yaml
* when pushing, upload index first with conditional PUT: add header `x-goog-if-generation-match:$revision`
* on error, to optionally retry, reload fresh index and run push again

See example: https://github.com/ausov/helm-gs/blob/3d994597fbddae7029ee0e3afad6d45796615761/bin/publish.sh#L72

**Comment by nouney** [comment]
Thanks @ausov for this issue. It is fixed in version 0.2.0.
