### ISSUE TITLE
Error when pushing packages to gcs repo

### ISSUE THREAD

**Issue by joe-boyce** [nouney/helm-gcs#4]
Hi,

We are currently receiving the following error when trying to run helm gcs push *package* *repo*, any ideas:

```Error: storage: object doesn't exist
Usage:
  helm-gcs push [chart] [repository] [flags]

Flags:
  -h, --help   help for push

storage: object doesn't exist
Error: plugin "gcs" exited with error

**Comment by nouney** [comment]
Hi,

Is there an `index.yaml` in your repo? (gs://your-bucket/your/path/index.yaml)
If so, open it and check if its contains a ref to your package in the `entries` field?

**Comment by joe-boyce** [comment]
Thanks for replying so quickly

Yeah it certainly does, here's a small snippet:

```apiVersion: v1
entries:
  api-cache:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-02-16T15:22:44.651287527Z
    description: A Helm chart for the api-cache tier
    digest: cc0c53e79509f24b0b68ca25f021efb9c955bbb6d8d02195f964cbcf2e97b976
    name: api-cache
    urls:
    - gs://helm-repo/_**reponame**_/api-cache-1.tgz
    version: "1"```

**Comment by nouney** [comment]
Thanks for the snippet. Was your package uploaded to your repo? 

I'll release a new version with more debug info (my bad about that) in an hour or so. I'll try to reproduce the error at the same time.

**Comment by joe-boyce** [comment]
Unfortunately no upload/changes

Sounds good, thanks again

**Comment by joe-boyce** [comment]
Sure no problem, debug output as follows:

```Error: repo.AddChartFile: repo.LoadIndexFile: gcs.NewReader: storage: object doesn't exist
Usage:
  helm-gcs push [chart] [repository] [flags]

Flags:
  -h, --help   help for push

Global Flags:
  -d, --debug   debug mode

repo.AddChartFile: repo.LoadIndexFile: gcs.NewReader: storage: object doesn't exist
Error: plugin "gcs" exited with error

**Comment by nouney** [comment]
That's weird, `helm-gcs` can't read `index.yaml` from your bucket.

If you run that command: `helm gcs push <package> <repo> -d`, you should see something like that at the beginning of the output:
```
helm: config dir: /home/nouney/.helm
gcs: create new reader for file '<REPO>/index.yaml' in bucket '<BUCKET>' (url: gs://<BUCKET>/<REPO>/index.yaml)
Error: repo.AddChartFile: repo.LoadIndexFile: gcs.NewReader: storage: object doesn't exist
Usage:
  <...>
```
Check if REPO and BUCKET are correct please. 
Just to be sure: have the authorizations on `index.yaml`  changed?

In the meantime, I may have a workaround: if you manually upload your package to your repo on GCS, you should still be able to use it directly from `helm` (fetch, install, etc).

**Comment by joe-boyce** [comment]
Ahhh thats exactly what I needed, thanks for adding debug into the tool as this highlighted the issue straight away.  Looks like when we added the repo to some new hosts they included a "/" at the end of the repo so it was including that in the call as <REPO>//index.yaml

Removed the repo and added without the trailing slash and all is working fine

Thanks again,

Joe

**Comment by nouney** [comment]
You're welcome.

I just released a new version that addresses this issue. The plugin will now handle URLs with a trailing slash.

**Comment by Pamir** [comment]
upload index.yaml with the values below
```yaml
apiVersion: v1
entries:
```
