### ISSUE TITLE
Init removes everything from the bucket

### ISSUE THREAD

**Issue by burdiyan** [nouney/helm-gcs#5]
I accidentally ran helm gcs init for a bucket that already was a helm repo, and found out that after that it was completely empty.

It would be great if the plugin could warn that the bucket is not empty before running this operation.

**Comment by madmod** [comment]
Making init idempotent or an automatic part push would be great for CI.

**Comment by nouney** [comment]
@burdiyan @madmod 

Thanks for reporting this issue and sorry for the delay. It is fixed in the new version:

```shell
$ helm plugin gcs update
$ helm gcs version
version: 0.1.4
commit: 519b95ca3d0bde2ac1654ecb6b4995663b2a2eb5
date: 2018-03-20T22:47:57Z
```
```
