### ISSUE TITLE
helm-gcs is incompatible with Landscaper

### ISSUE THREAD

**Issue by james-masson** [nouney/helm-gcs#7]
... or potentially anything that uses this Helm function - https://github.com/kubernetes/helm/blob/master/pkg/downloader/chart_downloader.go#L132

Please see this landscaper issue - https://github.com/Eneco/landscaper/issues/117

**Comment by james-masson** [comment]
Landscaper is calling this: https://github.com/kubernetes/helm/blob/master/pkg/downloader/chart_downloader.go#L132

Which leads to this: https://github.com/kubernetes/helm/blob/master/pkg/repo/chartrepo.go#L63

Which blows up, as it doesn't like the "gs" protocol.

**Comment by nouney** [comment]
Landscaper does not support helm plugins (see https://github.com/Eneco/landscaper/issues/117).
